services:
  mysql:
    image: mysql:8.0
    volumes:
      - todos-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    ports:
      - 3306:3306
volumes:
  todos-data:
