services:
  mysql:
    image: mysql:8.0
    volumes:
      - todos-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    ports:
      - 3306:3306
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: secret
    volumes:
      - todos-data:/data
volumes:
  todos-data:
  todos-data-redis:
